import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="p-6">
      <Head>
        <title>Habour Masters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center min-h-screen text-gray-400 font-semibold text-lg">
        Please select an option on the sidebar
      </div>
    </div>
  );
};

export default Home;
